# Justpy Tutorial demo input_demo 
# title       
#      
# generated by write_as_demo  at 2023-01-08T10:01:48.946997+00:00 
# 
# see https://justpy.io/reference/webpage#title
# see https://github.com/justpy-org/justpy/blob/master/docs/reference/webpage.md

import justpy as jp

input_classes = "m-2 bg-gray-200 border-2 border-gray-200 rounded w-64 py-2 px-4 text-gray-700 focus:outline-none focus:bg-white focus:border-purple-500"

async def input_demo(request):
    wp = jp.WebPage()

    def change_title_and_url(self, msg):
        msg.page.display_url = self.value
        msg.page.title = self.value

    in1 = jp.Input(a=wp, classes=input_classes, placeholder='Type here to change title and url', input=change_title_and_url)
    return wp

# initialize the demo
from examples.basedemo import Demo
Demo("input_demo", input_demo)
