# Justpy Tutorial demo test_head 
# head_html and body_html       
#      
# generated by write_as_demo  at 2023-01-08T10:02:16.085796+00:00 
# 
# see https://justpy.io/reference/webpage#head_html-and-body_html
# see https://github.com/justpy-org/justpy/blob/master/docs/reference/webpage.md

import justpy as jp

def test_head():
    wp = jp.WebPage()
    wp.head_html = '<script>console.log("Hello there from head");</script>'
    wp.body_html = '<script>console.log("Hello there from body");</script>'
    jp.Div(text='Testing...', a=wp)
    return wp

# initialize the demo
from examples.basedemo import Demo
Demo("test_head", test_head)
