# Justpy Tutorial demo grid_test17 
# load women_majors.csv with pandas       
#      
# generated by write_as_demo  at 2022-12-18T15:18:06.514524+00:00 
# 
# see https://justpy.io/grids_tutorial/pandas#load-women_majorscsv-with-pandas
# see https://github.com/justpy-org/justpy/blob/master/docs/grids_tutorial/pandas.md

import justpy as jp
import pandas as pd

wm_df = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)

def grid_test17():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, auto_size=True, style = "height: 99vh; width: 100%", theme='ag-theme-material')
    grid.load_pandas_frame(wm_df)
    print(grid.options.rowData)
    return wp

# initialize the demo
from examples.basedemo import Demo
Demo("grid_test17", grid_test17)
