
# https://tailwindcss.com/docs/installation/
# https://tailwind.run/new
# https://nervous-knuth-fa9c3e.netlify.com/   additional form classes form-radio etc. Already added CSS
class Tailwind:

    pseudo_classes = ['hover', 'focus', 'active', 'group-hover', 'focus-within']

    tw_dict = {'container': ['container'],
           'display': ['block', 'inline-block', 'inline', 'flex', 'inline-flex', 'table', 'table-row', 'table-cell',
                       'hidden'], 'float': ['float-right', 'float-left', 'float-none', 'clearfix'],
           'object_fit': ['object-contain', 'object-cover', 'object-fill', 'object-none', 'object-scale-down'],
           'object_position': ['object-bottom', 'object-center', 'object-left', 'object-left-bottom', 'object-left-top',
                               'object-right', 'object-right-bottom', 'object-right-top', 'object-top'],
           'overflow': ['overflow-auto', 'overflow-hidden', 'overflow-visible', 'overflow-scroll', 'overflow-x-auto',
                        'overflow-y-auto', 'overflow-x-hidden', 'overflow-y-hidden', 'overflow-x-visible',
                        'overflow-y-visible', 'overflow-x-scroll', 'overflow-y-scroll', 'scrolling-touch',
                        'scrolling-auto'], 'position': ['static', 'fixed', 'absolute', 'relative', 'sticky'],
           'top_right_bottom_left': ['inset-0', 'inset-y-0', 'inset-x-0', 'top-0', 'right-0', 'bottom-0', 'left-0',
                                     'inset-auto', 'inset-y-auto', 'inset-x-auto', 'top-auto', 'bottom-auto',
                                     'left-auto', 'right-auto'], 'visibility': ['visible', 'invisible'],
           'z_index': ['z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto'],
           'font_family': ['font-sans', 'font-serif', 'font-mono'],
           'font_size': ['text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl',
                         'text-5xl', 'text-6xl'], 'font_smoothing': ['antialiased', 'subpixel-antialiased'],
           'font_style': ['italic', 'not-italic'],
           'font_weight': ['font-hairline', 'font-thin', 'font-light', 'font-normal', 'font-medium', 'font-semibold',
                           'font-bold', 'font-extrabold', 'font-black'],
           'letter_spacing': ['tracking-tighter', 'tracking-tight', 'tracking-normal', 'tracking-wide',
                              'tracking-wider', 'tracking-widest'],
           'line_height': ['leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed',
                           'leading-loose'], 'list_style_type': ['list-none', 'list-disc', 'list-decimal'],
           'list_style_position': ['list-inside', 'list-outside'],
           'text_align': ['text-left', 'text-center', 'text-right', 'text-justify'],
           'text_color': ['text-transparent', 'text-black', 'text-white', 'text-gray-100', 'text-gray-200',
                          'text-gray-300', 'text-gray-400', 'text-gray-500', 'text-gray-600', 'text-gray-700',
                          'text-gray-800', 'text-gray-900', 'text-red-100', 'text-red-200', 'text-red-300',
                          'text-red-400', 'text-red-500', 'text-red-600', 'text-red-700', 'text-red-800',
                          'text-red-900', 'text-orange-100', 'text-orange-200', 'text-orange-300', 'text-orange-400',
                          'text-orange-500', 'text-orange-600', 'text-orange-700', 'text-orange-800', 'text-orange-900',
                          'text-yellow-100', 'text-yellow-200', 'text-yellow-300', 'text-yellow-400', 'text-yellow-500',
                          'text-yellow-600', 'text-yellow-700', 'text-yellow-800', 'text-yellow-900', 'text-green-100',
                          'text-green-200', 'text-green-300', 'text-green-400', 'text-green-500', 'text-green-600',
                          'text-green-700', 'text-green-800', 'text-green-900', 'text-teal-100', 'text-teal-200',
                          'text-teal-300', 'text-teal-400', 'text-teal-500', 'text-teal-600', 'text-teal-700',
                          'text-teal-800', 'text-teal-900', 'text-blue-100', 'text-blue-200', 'text-blue-300',
                          'text-blue-400', 'text-blue-500', 'text-blue-600', 'text-blue-700', 'text-blue-800',
                          'text-blue-900', 'text-indigo-100', 'text-indigo-200', 'text-indigo-300', 'text-indigo-400',
                          'text-indigo-500', 'text-indigo-600', 'text-indigo-700', 'text-indigo-800', 'text-indigo-900',
                          'text-purple-100', 'text-purple-200', 'text-purple-300', 'text-purple-400', 'text-purple-500',
                          'text-purple-600', 'text-purple-700', 'text-purple-800', 'text-purple-900', 'text-pink-100',
                          'text-pink-200', 'text-pink-300', 'text-pink-400', 'text-pink-500', 'text-pink-600',
                          'text-pink-700', 'text-pink-800', 'text-pink-900'],
           'text_decoration': ['underline', 'line-through', 'no-underline'],
           'text_transform': ['uppercase', 'lowercase', 'capitalize', 'normal-case'],
           'vertical_align': ['align-baseline', 'align-top', 'align-middle', 'align-bottom', 'align-text-top',
                              'align-text-bottom'],
           'whitespace': ['whitespace-normal', 'whitespace-no-wrap', 'whitespace-pre', 'whitespace-pre-line',
                          'whitespace-pre-wrap'],
           'word_break': ['break-normal', 'break-words', 'break-all', 'truncate'],
           'background_attachment': ['bg-fixed', 'bg-local', 'bg-scroll'],
           'background_color': ['bg-transparent', 'bg-black', 'bg-white', 'bg-gray-100', 'bg-gray-200', 'bg-gray-300',
                                'bg-gray-400', 'bg-gray-500', 'bg-gray-600', 'bg-gray-700', 'bg-gray-800',
                                'bg-gray-900', 'bg-red-100', 'bg-red-200', 'bg-red-300', 'bg-red-400', 'bg-red-500',
                                'bg-red-600', 'bg-red-700', 'bg-red-800', 'bg-red-900', 'bg-orange-100',
                                'bg-orange-200', 'bg-orange-300', 'bg-orange-400', 'bg-orange-500', 'bg-orange-600',
                                'bg-orange-700', 'bg-orange-800', 'bg-orange-900', 'bg-yellow-100', 'bg-yellow-200',
                                'bg-yellow-300', 'bg-yellow-400', 'bg-yellow-500', 'bg-yellow-600', 'bg-yellow-700',
                                'bg-yellow-800', 'bg-yellow-900', 'bg-green-100', 'bg-green-200', 'bg-green-300',
                                'bg-green-400', 'bg-green-500', 'bg-green-600', 'bg-green-700', 'bg-green-800',
                                'bg-green-900', 'bg-teal-100', 'bg-teal-200', 'bg-teal-300', 'bg-teal-400',
                                'bg-teal-500', 'bg-teal-600', 'bg-teal-700', 'bg-teal-800', 'bg-teal-900',
                                'bg-blue-100', 'bg-blue-200', 'bg-blue-300', 'bg-blue-400', 'bg-blue-500',
                                'bg-blue-600', 'bg-blue-700', 'bg-blue-800', 'bg-blue-900', 'bg-indigo-100',
                                'bg-indigo-200', 'bg-indigo-300', 'bg-indigo-400', 'bg-indigo-500', 'bg-indigo-600',
                                'bg-indigo-700', 'bg-indigo-800', 'bg-indigo-900', 'bg-purple-100', 'bg-purple-200',
                                'bg-purple-300', 'bg-purple-400', 'bg-purple-500', 'bg-purple-600', 'bg-purple-700',
                                'bg-purple-800', 'bg-purple-900', 'bg-pink-100', 'bg-pink-200', 'bg-pink-300',
                                'bg-pink-400', 'bg-pink-500', 'bg-pink-600', 'bg-pink-700', 'bg-pink-800',
                                'bg-pink-900'],
           'background_position': ['bg-bottom', 'bg-center', 'bg-left', 'bg-left-bottom', 'bg-left-top', 'bg-right',
                                   'bg-right-bottom', 'bg-right-top', 'bg-top'],
           'background_repeat': ['bg-repeat', 'bg-no-repeat', 'bg-repeat-x', 'bg-repeat-y', 'bg-repeat-round',
                                 'bg-repeat-space'], 'background_size': ['bg-auto', 'bg-cover', 'bg-contain'],
           'border_color': ['border-transparent', 'border-black', 'border-white', 'border-gray-100', 'border-gray-200',
                            'border-gray-300', 'border-gray-400', 'border-gray-500', 'border-gray-600',
                            'border-gray-700', 'border-gray-800', 'border-gray-900', 'border-red-100', 'border-red-200',
                            'border-red-300', 'border-red-400', 'border-red-500', 'border-red-600', 'border-red-700',
                            'border-red-800', 'border-red-900', 'border-orange-100', 'border-orange-200',
                            'border-orange-300', 'border-orange-400', 'border-orange-500', 'border-orange-600',
                            'border-orange-700', 'border-orange-800', 'border-orange-900', 'border-yellow-100',
                            'border-yellow-200', 'border-yellow-300', 'border-yellow-400', 'border-yellow-500',
                            'border-yellow-600', 'border-yellow-700', 'border-yellow-800', 'border-yellow-900',
                            'border-green-100', 'border-green-200', 'border-green-300', 'border-green-400',
                            'border-green-500', 'border-green-600', 'border-green-700', 'border-green-800',
                            'border-green-900', 'border-teal-100', 'border-teal-200', 'border-teal-300',
                            'border-teal-400', 'border-teal-500', 'border-teal-600', 'border-teal-700',
                            'border-teal-800', 'border-teal-900', 'border-blue-100', 'border-blue-200',
                            'border-blue-300', 'border-blue-400', 'border-blue-500', 'border-blue-600',
                            'border-blue-700', 'border-blue-800', 'border-blue-900', 'border-indigo-100',
                            'border-indigo-200', 'border-indigo-300', 'border-indigo-400', 'border-indigo-500',
                            'border-indigo-600', 'border-indigo-700', 'border-indigo-800', 'border-indigo-900',
                            'border-purple-100', 'border-purple-200', 'border-purple-300', 'border-purple-400',
                            'border-purple-500', 'border-purple-600', 'border-purple-700', 'border-purple-800',
                            'border-purple-900', 'border-pink-100', 'border-pink-200', 'border-pink-300',
                            'border-pink-400', 'border-pink-500', 'border-pink-600', 'border-pink-700',
                            'border-pink-800', 'border-pink-900'],
           'border_style': ['border-solid', 'border-dashed', 'border-dotted', 'border-none'],
           'border_width': ['border', 'border-0', 'border-2', 'border-4', 'border-8', 'border-t', 'border-r',
                            'border-b', 'border-l', 'border-t-0', 'border-r-0', 'border-b-0', 'border-l-0',
                            'border-t-2', 'border-r-2', 'border-b-2', 'border-l-2', 'border-t-4', 'border-r-4',
                            'border-b-4', 'border-l-4', 'border-t-8', 'border-r-8', 'border-b-8', 'border-l-8'],
           'border_radius': ['rounded-none', 'rounded-sm', 'rounded', 'rounded-lg', 'rounded-full', 'rounded-t-none',
                             'rounded-r-none', 'rounded-b-none', 'rounded-l-none', 'rounded-t-sm', 'rounded-r-sm',
                             'rounded-b-sm', 'rounded-l-sm', 'rounded-t', 'rounded-r', 'rounded-b', 'rounded-l',
                             'rounded-t-lg', 'rounded-r-lg', 'rounded-b-lg', 'rounded-l-lg', 'rounded-t-full',
                             'rounded-r-full', 'rounded-b-full', 'rounded-l-full', 'rounded-tl-none', 'rounded-tr-none',
                             'rounded-br-none', 'rounded-bl-none', 'rounded-tl-sm', 'rounded-tr-sm', 'rounded-br-sm',
                             'rounded-bl-sm', 'rounded-tl', 'rounded-tr', 'rounded-br', 'rounded-bl', 'rounded-tl-lg',
                             'rounded-tr-lg', 'rounded-br-lg', 'rounded-bl-lg', 'rounded-tl-full', 'rounded-tr-full',
                             'rounded-br-full', 'rounded-bl-full'],
           'flex_direction': ['flex-row', 'flex-row-reverse', 'flex-col', 'flex-col-reverse'],
           'flex_wrap': ['flex-no-wrap', 'flex-wrap', 'flex-wrap-reverse'],
           'align_items': ['items-stretch', 'items-start', 'items-center', 'items-end', 'items-baseline'],
           'align_content': ['content-start', 'content-center', 'content-end', 'content-between', 'content-around'],
           'align_self': ['self-auto', 'self-start', 'self-center', 'self-end', 'self-stretch'],
           'justify_content': ['justify-start', 'justify-center', 'justify-end', 'justify-between', 'justify-around'],
           'flex': ['flex-initial', 'flex-1', 'flex-auto', 'flex-none'], 'flex_grow': ['flex-grow', 'flex-grow-0'],
           'flex_shrink': ['flex-shrink', 'flex-shrink-0'],
           'order': ['order-first', 'order-last', 'order-none', 'order-1', 'order-2', 'order-3', 'order-4', 'order-5',
                     'order-6', 'order-7', 'order-8', 'order-9', 'order-10', 'order-11', 'order-12'],
           'padding': ['p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12', 'p-16', 'p-20', 'p-24',
                       'p-32', 'p-40', 'p-48', 'p-56', 'p-64', 'p-px', 'py-0', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5',
                       'py-6', 'py-8', 'py-10', 'py-12', 'py-16', 'py-20', 'py-24', 'py-32', 'py-40', 'py-48', 'py-56',
                       'py-64', 'py-px', 'px-0', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8', 'px-10',
                       'px-12', 'px-16', 'px-20', 'px-24', 'px-32', 'px-40', 'px-48', 'px-56', 'px-64', 'px-px', 'pt-0',
                       'pt-1', 'pt-2', 'pt-3', 'pt-4', 'pt-5', 'pt-6', 'pt-8', 'pt-10', 'pt-12', 'pt-16', 'pt-20',
                       'pt-24', 'pt-32', 'pt-40', 'pt-48', 'pt-56', 'pt-64', 'pt-px', 'pr-0', 'pr-1', 'pr-2', 'pr-3',
                       'pr-4', 'pr-5', 'pr-6', 'pr-8', 'pr-10', 'pr-12', 'pr-16', 'pr-20', 'pr-24', 'pr-32', 'pr-40',
                       'pr-48', 'pr-56', 'pr-64', 'pr-px', 'pb-0', 'pb-1', 'pb-2', 'pb-3', 'pb-4', 'pb-5', 'pb-6',
                       'pb-8', 'pb-10', 'pb-12', 'pb-16', 'pb-20', 'pb-24', 'pb-32', 'pb-40', 'pb-48', 'pb-56', 'pb-64',
                       'pb-px', 'pl-0', 'pl-1', 'pl-2', 'pl-3', 'pl-4', 'pl-5', 'pl-6', 'pl-8', 'pl-10', 'pl-12',
                       'pl-16', 'pl-20', 'pl-24', 'pl-32', 'pl-40', 'pl-48', 'pl-56', 'pl-64', 'pl-px'],
           'margin': ['m-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-8', 'm-10', 'm-12', 'm-16', 'm-20', 'm-24',
                      'm-32', 'm-40', 'm-48', 'm-56', 'm-64', 'm-auto', 'm-px', '-m-1', '-m-2', '-m-3', '-m-4', '-m-5',
                      '-m-6', '-m-8', '-m-10', '-m-12', '-m-16', '-m-20', '-m-24', '-m-32', '-m-40', '-m-48', '-m-56',
                      '-m-64', '-m-px', 'my-0', 'my-1', 'my-2', 'my-3', 'my-4', 'my-5', 'my-6', 'my-8', 'my-10',
                      'my-12', 'my-16', 'my-20', 'my-24', 'my-32', 'my-40', 'my-48', 'my-56', 'my-64', 'my-auto',
                      'my-px', '-my-1', '-my-2', '-my-3', '-my-4', '-my-5', '-my-6', '-my-8', '-my-10', '-my-12',
                      '-my-16', '-my-20', '-my-24', '-my-32', '-my-40', '-my-48', '-my-56', '-my-64', '-my-px', 'mx-0',
                      'mx-1', 'mx-2', 'mx-3', 'mx-4', 'mx-5', 'mx-6', 'mx-8', 'mx-10', 'mx-12', 'mx-16', 'mx-20',
                      'mx-24', 'mx-32', 'mx-40', 'mx-48', 'mx-56', 'mx-64', 'mx-auto', 'mx-px', '-mx-1', '-mx-2',
                      '-mx-3', '-mx-4', '-mx-5', '-mx-6', '-mx-8', '-mx-10', '-mx-12', '-mx-16', '-mx-20', '-mx-24',
                      '-mx-32', '-mx-40', '-mx-48', '-mx-56', '-mx-64', '-mx-px', 'mt-0', 'mt-1', 'mt-2', 'mt-3',
                      'mt-4', 'mt-5', 'mt-6', 'mt-8', 'mt-10', 'mt-12', 'mt-16', 'mt-20', 'mt-24', 'mt-32', 'mt-40',
                      'mt-48', 'mt-56', 'mt-64', 'mt-auto', 'mt-px', '-mt-1', '-mt-2', '-mt-3', '-mt-4', '-mt-5',
                      '-mt-6', '-mt-8', '-mt-10', '-mt-12', '-mt-16', '-mt-20', '-mt-24', '-mt-32', '-mt-40', '-mt-48',
                      '-mt-56', '-mt-64', '-mt-px', 'mr-0', 'mr-1', 'mr-2', 'mr-3', 'mr-4', 'mr-5', 'mr-6', 'mr-8',
                      'mr-10', 'mr-12', 'mr-16', 'mr-20', 'mr-24', 'mr-32', 'mr-40', 'mr-48', 'mr-56', 'mr-64',
                      'mr-auto', 'mr-px', '-mr-1', '-mr-2', '-mr-3', '-mr-4', '-mr-5', '-mr-6', '-mr-8', '-mr-10',
                      '-mr-12', '-mr-16', '-mr-20', '-mr-24', '-mr-32', '-mr-40', '-mr-48', '-mr-56', '-mr-64',
                      '-mr-px', 'mb-0', 'mb-1', 'mb-2', 'mb-3', 'mb-4', 'mb-5', 'mb-6', 'mb-8', 'mb-10', 'mb-12',
                      'mb-16', 'mb-20', 'mb-24', 'mb-32', 'mb-40', 'mb-48', 'mb-56', 'mb-64', 'mb-auto', 'mb-px',
                      '-mb-1', '-mb-2', '-mb-3', '-mb-4', '-mb-5', '-mb-6', '-mb-8', '-mb-10', '-mb-12', '-mb-16',
                      '-mb-20', '-mb-24', '-mb-32', '-mb-40', '-mb-48', '-mb-56', '-mb-64', '-mb-px', 'ml-0', 'ml-1',
                      'ml-2', 'ml-3', 'ml-4', 'ml-5', 'ml-6', 'ml-8', 'ml-10', 'ml-12', 'ml-16', 'ml-20', 'ml-24',
                      'ml-32', 'ml-40', 'ml-48', 'ml-56', 'ml-64', 'ml-auto', 'ml-px', '-ml-1', '-ml-2', '-ml-3',
                      '-ml-4', '-ml-5', '-ml-6', '-ml-8', '-ml-10', '-ml-12', '-ml-16', '-ml-20', '-ml-24', '-ml-32',
                      '-ml-40', '-ml-48', '-ml-56', '-ml-64', '-ml-px'],
           'width': ['w-0', 'w-1', 'w-2', 'w-3', 'w-4', 'w-5', 'w-6', 'w-8', 'w-10', 'w-12', 'w-16', 'w-20', 'w-24',
                     'w-32', 'w-40', 'w-48', 'w-56', 'w-64', 'w-auto', 'w-px', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4',
                     'w-2/4', 'w-3/4', 'w-1/5', 'w-2/5', 'w-3/5', 'w-4/5', 'w-1/6', 'w-2/6', 'w-3/6', 'w-4/6', 'w-5/6',
                     'w-1/12', 'w-2/12', 'w-3/12', 'w-4/12', 'w-5/12', 'w-6/12', 'w-7/12', 'w-8/12', 'w-9/12',
                     'w-10/12', 'w-11/12', 'w-full', 'w-screen'], 'min_width': ['min-w-0', 'min-w-full'],
           'max_width': ['max-w-xs', 'max-w-sm', 'max-w-md', 'max-w-lg', 'max-w-xl', 'max-w-2xl', 'max-w-3xl',
                         'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-full'],
           'height': ['h-0', 'h-1', 'h-2', 'h-3', 'h-4', 'h-5', 'h-6', 'h-8', 'h-10', 'h-12', 'h-16', 'h-20', 'h-24',
                      'h-32', 'h-40', 'h-48', 'h-56', 'h-64', 'h-auto', 'h-px', 'h-full', 'h-screen'],
           'min_height': ['min-h-0', 'min-h-full', 'min-h-screen'], 'max_height': ['max-h-full', 'max-h-screen'],
           'border_collapse': ['border-collapse', 'border-separate'], 'table_layout': ['table-auto', 'table-fixed'],
           'box_shadow': ['shadow', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-inner',
                          'shadow-outline', 'shadow-none'],
           'opacity': ['opacity-100', 'opacity-75', 'opacity-50', 'opacity-25', 'opacity-0'],
           'appearance': ['appearance-none'],
           'cursor': ['cursor-auto', 'cursor-default', 'cursor-pointer', 'cursor-wait', 'cursor-text', 'cursor-move',
                      'cursor-not-allowed'], 'outline': ['outline-none'],
           'pointer_events': ['pointer-events-none', 'pointer-events-auto'],
           'resize': ['resize-none', 'resize', 'resize-y', 'resize-x'],
           'user_select': ['select-none', 'select-text', 'select-all', 'select-auto'], 'fill': ['fill-current'],
           'stroke': ['stroke-current']}

    tw_reverse_dict = {'container': 'container', 'block': 'display', 'inline-block': 'display', 'inline': 'display',
                  'flex': 'display', 'inline-flex': 'display', 'table': 'display', 'table-row': 'display',
                  'table-cell': 'display', 'hidden': 'display', 'float-right': 'float', 'float-left': 'float',
                  'float-none': 'float', 'clearfix': 'float', 'object-contain': 'object_fit',
                  'object-cover': 'object_fit', 'object-fill': 'object_fit', 'object-none': 'object_fit',
                  'object-scale-down': 'object_fit', 'object-bottom': 'object_position',
                  'object-center': 'object_position', 'object-left': 'object_position',
                  'object-left-bottom': 'object_position', 'object-left-top': 'object_position',
                  'object-right': 'object_position', 'object-right-bottom': 'object_position',
                  'object-right-top': 'object_position', 'object-top': 'object_position', 'overflow-auto': 'overflow',
                  'overflow-hidden': 'overflow', 'overflow-visible': 'overflow', 'overflow-scroll': 'overflow',
                  'overflow-x-auto': 'overflow', 'overflow-y-auto': 'overflow', 'overflow-x-hidden': 'overflow',
                  'overflow-y-hidden': 'overflow', 'overflow-x-visible': 'overflow', 'overflow-y-visible': 'overflow',
                  'overflow-x-scroll': 'overflow', 'overflow-y-scroll': 'overflow', 'scrolling-touch': 'overflow',
                  'scrolling-auto': 'overflow', 'static': 'position', 'fixed': 'position', 'absolute': 'position',
                  'relative': 'position', 'sticky': 'position', 'inset-0': 'top_right_bottom_left',
                  'inset-y-0': 'top_right_bottom_left', 'inset-x-0': 'top_right_bottom_left',
                  'top-0': 'top_right_bottom_left', 'right-0': 'top_right_bottom_left',
                  'bottom-0': 'top_right_bottom_left', 'left-0': 'top_right_bottom_left',
                  'inset-auto': 'top_right_bottom_left', 'inset-y-auto': 'top_right_bottom_left',
                  'inset-x-auto': 'top_right_bottom_left', 'top-auto': 'top_right_bottom_left',
                  'bottom-auto': 'top_right_bottom_left', 'left-auto': 'top_right_bottom_left',
                  'right-auto': 'top_right_bottom_left', 'visible': 'visibility', 'invisible': 'visibility',
                  'z-0': 'z_index', 'z-10': 'z_index', 'z-20': 'z_index', 'z-30': 'z_index', 'z-40': 'z_index',
                  'z-50': 'z_index', 'z-auto': 'z_index', 'font-sans': 'font_family', 'font-serif': 'font_family',
                  'font-mono': 'font_family', 'text-xs': 'font_size', 'text-sm': 'font_size', 'text-base': 'font_size',
                  'text-lg': 'font_size', 'text-xl': 'font_size', 'text-2xl': 'font_size', 'text-3xl': 'font_size',
                  'text-4xl': 'font_size', 'text-5xl': 'font_size', 'text-6xl': 'font_size',
                  'antialiased': 'font_smoothing', 'subpixel-antialiased': 'font_smoothing', 'italic': 'font_style',
                  'not-italic': 'font_style', 'font-hairline': 'font_weight', 'font-thin': 'font_weight',
                  'font-light': 'font_weight', 'font-normal': 'font_weight', 'font-medium': 'font_weight',
                  'font-semibold': 'font_weight', 'font-bold': 'font_weight', 'font-extrabold': 'font_weight',
                  'font-black': 'font_weight', 'tracking-tighter': 'letter_spacing', 'tracking-tight': 'letter_spacing',
                  'tracking-normal': 'letter_spacing', 'tracking-wide': 'letter_spacing',
                  'tracking-wider': 'letter_spacing', 'tracking-widest': 'letter_spacing',
                  'leading-none': 'line_height', 'leading-tight': 'line_height', 'leading-snug': 'line_height',
                  'leading-normal': 'line_height', 'leading-relaxed': 'line_height', 'leading-loose': 'line_height',
                  'list-none': 'list_style_type', 'list-disc': 'list_style_type', 'list-decimal': 'list_style_type',
                  'list-inside': 'list_style_position', 'list-outside': 'list_style_position',
                  'text-left': 'text_align', 'text-center': 'text_align', 'text-right': 'text_align',
                  'text-justify': 'text_align', 'text-transparent': 'text_color', 'text-black': 'text_color',
                  'text-white': 'text_color', 'text-gray-100': 'text_color', 'text-gray-200': 'text_color',
                  'text-gray-300': 'text_color', 'text-gray-400': 'text_color', 'text-gray-500': 'text_color',
                  'text-gray-600': 'text_color', 'text-gray-700': 'text_color', 'text-gray-800': 'text_color',
                  'text-gray-900': 'text_color', 'text-red-100': 'text_color', 'text-red-200': 'text_color',
                  'text-red-300': 'text_color', 'text-red-400': 'text_color', 'text-red-500': 'text_color',
                  'text-red-600': 'text_color', 'text-red-700': 'text_color', 'text-red-800': 'text_color',
                  'text-red-900': 'text_color', 'text-orange-100': 'text_color', 'text-orange-200': 'text_color',
                  'text-orange-300': 'text_color', 'text-orange-400': 'text_color', 'text-orange-500': 'text_color',
                  'text-orange-600': 'text_color', 'text-orange-700': 'text_color', 'text-orange-800': 'text_color',
                  'text-orange-900': 'text_color', 'text-yellow-100': 'text_color', 'text-yellow-200': 'text_color',
                  'text-yellow-300': 'text_color', 'text-yellow-400': 'text_color', 'text-yellow-500': 'text_color',
                  'text-yellow-600': 'text_color', 'text-yellow-700': 'text_color', 'text-yellow-800': 'text_color',
                  'text-yellow-900': 'text_color', 'text-green-100': 'text_color', 'text-green-200': 'text_color',
                  'text-green-300': 'text_color', 'text-green-400': 'text_color', 'text-green-500': 'text_color',
                  'text-green-600': 'text_color', 'text-green-700': 'text_color', 'text-green-800': 'text_color',
                  'text-green-900': 'text_color', 'text-teal-100': 'text_color', 'text-teal-200': 'text_color',
                  'text-teal-300': 'text_color', 'text-teal-400': 'text_color', 'text-teal-500': 'text_color',
                  'text-teal-600': 'text_color', 'text-teal-700': 'text_color', 'text-teal-800': 'text_color',
                  'text-teal-900': 'text_color', 'text-blue-100': 'text_color', 'text-blue-200': 'text_color',
                  'text-blue-300': 'text_color', 'text-blue-400': 'text_color', 'text-blue-500': 'text_color',
                  'text-blue-600': 'text_color', 'text-blue-700': 'text_color', 'text-blue-800': 'text_color',
                  'text-blue-900': 'text_color', 'text-indigo-100': 'text_color', 'text-indigo-200': 'text_color',
                  'text-indigo-300': 'text_color', 'text-indigo-400': 'text_color', 'text-indigo-500': 'text_color',
                  'text-indigo-600': 'text_color', 'text-indigo-700': 'text_color', 'text-indigo-800': 'text_color',
                  'text-indigo-900': 'text_color', 'text-purple-100': 'text_color', 'text-purple-200': 'text_color',
                  'text-purple-300': 'text_color', 'text-purple-400': 'text_color', 'text-purple-500': 'text_color',
                  'text-purple-600': 'text_color', 'text-purple-700': 'text_color', 'text-purple-800': 'text_color',
                  'text-purple-900': 'text_color', 'text-pink-100': 'text_color', 'text-pink-200': 'text_color',
                  'text-pink-300': 'text_color', 'text-pink-400': 'text_color', 'text-pink-500': 'text_color',
                  'text-pink-600': 'text_color', 'text-pink-700': 'text_color', 'text-pink-800': 'text_color',
                  'text-pink-900': 'text_color', 'underline': 'text_decoration', 'line-through': 'text_decoration',
                  'no-underline': 'text_decoration', 'uppercase': 'text_transform', 'lowercase': 'text_transform',
                  'capitalize': 'text_transform', 'normal-case': 'text_transform', 'align-baseline': 'vertical_align',
                  'align-top': 'vertical_align', 'align-middle': 'vertical_align', 'align-bottom': 'vertical_align',
                  'align-text-top': 'vertical_align', 'align-text-bottom': 'vertical_align',
                  'whitespace-normal': 'whitespace', 'whitespace-no-wrap': 'whitespace', 'whitespace-pre': 'whitespace',
                  'whitespace-pre-line': 'whitespace', 'whitespace-pre-wrap': 'whitespace',
                  'break-normal': 'word_break', 'break-words': 'word_break', 'break-all': 'word_break',
                  'truncate': 'word_break', 'bg-fixed': 'background_attachment', 'bg-local': 'background_attachment',
                  'bg-scroll': 'background_attachment', 'bg-transparent': 'background_color',
                  'bg-black': 'background_color', 'bg-white': 'background_color', 'bg-gray-100': 'background_color',
                  'bg-gray-200': 'background_color', 'bg-gray-300': 'background_color',
                  'bg-gray-400': 'background_color', 'bg-gray-500': 'background_color',
                  'bg-gray-600': 'background_color', 'bg-gray-700': 'background_color',
                  'bg-gray-800': 'background_color', 'bg-gray-900': 'background_color',
                  'bg-red-100': 'background_color', 'bg-red-200': 'background_color', 'bg-red-300': 'background_color',
                  'bg-red-400': 'background_color', 'bg-red-500': 'background_color', 'bg-red-600': 'background_color',
                  'bg-red-700': 'background_color', 'bg-red-800': 'background_color', 'bg-red-900': 'background_color',
                  'bg-orange-100': 'background_color', 'bg-orange-200': 'background_color',
                  'bg-orange-300': 'background_color', 'bg-orange-400': 'background_color',
                  'bg-orange-500': 'background_color', 'bg-orange-600': 'background_color',
                  'bg-orange-700': 'background_color', 'bg-orange-800': 'background_color',
                  'bg-orange-900': 'background_color', 'bg-yellow-100': 'background_color',
                  'bg-yellow-200': 'background_color', 'bg-yellow-300': 'background_color',
                  'bg-yellow-400': 'background_color', 'bg-yellow-500': 'background_color',
                  'bg-yellow-600': 'background_color', 'bg-yellow-700': 'background_color',
                  'bg-yellow-800': 'background_color', 'bg-yellow-900': 'background_color',
                  'bg-green-100': 'background_color', 'bg-green-200': 'background_color',
                  'bg-green-300': 'background_color', 'bg-green-400': 'background_color',
                  'bg-green-500': 'background_color', 'bg-green-600': 'background_color',
                  'bg-green-700': 'background_color', 'bg-green-800': 'background_color',
                  'bg-green-900': 'background_color', 'bg-teal-100': 'background_color',
                  'bg-teal-200': 'background_color', 'bg-teal-300': 'background_color',
                  'bg-teal-400': 'background_color', 'bg-teal-500': 'background_color',
                  'bg-teal-600': 'background_color', 'bg-teal-700': 'background_color',
                  'bg-teal-800': 'background_color', 'bg-teal-900': 'background_color',
                  'bg-blue-100': 'background_color', 'bg-blue-200': 'background_color',
                  'bg-blue-300': 'background_color', 'bg-blue-400': 'background_color',
                  'bg-blue-500': 'background_color', 'bg-blue-600': 'background_color',
                  'bg-blue-700': 'background_color', 'bg-blue-800': 'background_color',
                  'bg-blue-900': 'background_color', 'bg-indigo-100': 'background_color',
                  'bg-indigo-200': 'background_color', 'bg-indigo-300': 'background_color',
                  'bg-indigo-400': 'background_color', 'bg-indigo-500': 'background_color',
                  'bg-indigo-600': 'background_color', 'bg-indigo-700': 'background_color',
                  'bg-indigo-800': 'background_color', 'bg-indigo-900': 'background_color',
                  'bg-purple-100': 'background_color', 'bg-purple-200': 'background_color',
                  'bg-purple-300': 'background_color', 'bg-purple-400': 'background_color',
                  'bg-purple-500': 'background_color', 'bg-purple-600': 'background_color',
                  'bg-purple-700': 'background_color', 'bg-purple-800': 'background_color',
                  'bg-purple-900': 'background_color', 'bg-pink-100': 'background_color',
                  'bg-pink-200': 'background_color', 'bg-pink-300': 'background_color',
                  'bg-pink-400': 'background_color', 'bg-pink-500': 'background_color',
                  'bg-pink-600': 'background_color', 'bg-pink-700': 'background_color',
                  'bg-pink-800': 'background_color', 'bg-pink-900': 'background_color',
                  'bg-bottom': 'background_position', 'bg-center': 'background_position',
                  'bg-left': 'background_position', 'bg-left-bottom': 'background_position',
                  'bg-left-top': 'background_position', 'bg-right': 'background_position',
                  'bg-right-bottom': 'background_position', 'bg-right-top': 'background_position',
                  'bg-top': 'background_position', 'bg-repeat': 'background_repeat',
                  'bg-no-repeat': 'background_repeat', 'bg-repeat-x': 'background_repeat',
                  'bg-repeat-y': 'background_repeat', 'bg-repeat-round': 'background_repeat',
                  'bg-repeat-space': 'background_repeat', 'bg-auto': 'background_size', 'bg-cover': 'background_size',
                  'bg-contain': 'background_size', 'border-transparent': 'border_color', 'border-black': 'border_color',
                  'border-white': 'border_color', 'border-gray-100': 'border_color', 'border-gray-200': 'border_color',
                  'border-gray-300': 'border_color', 'border-gray-400': 'border_color',
                  'border-gray-500': 'border_color', 'border-gray-600': 'border_color',
                  'border-gray-700': 'border_color', 'border-gray-800': 'border_color',
                  'border-gray-900': 'border_color', 'border-red-100': 'border_color', 'border-red-200': 'border_color',
                  'border-red-300': 'border_color', 'border-red-400': 'border_color', 'border-red-500': 'border_color',
                  'border-red-600': 'border_color', 'border-red-700': 'border_color', 'border-red-800': 'border_color',
                  'border-red-900': 'border_color', 'border-orange-100': 'border_color',
                  'border-orange-200': 'border_color', 'border-orange-300': 'border_color',
                  'border-orange-400': 'border_color', 'border-orange-500': 'border_color',
                  'border-orange-600': 'border_color', 'border-orange-700': 'border_color',
                  'border-orange-800': 'border_color', 'border-orange-900': 'border_color',
                  'border-yellow-100': 'border_color', 'border-yellow-200': 'border_color',
                  'border-yellow-300': 'border_color', 'border-yellow-400': 'border_color',
                  'border-yellow-500': 'border_color', 'border-yellow-600': 'border_color',
                  'border-yellow-700': 'border_color', 'border-yellow-800': 'border_color',
                  'border-yellow-900': 'border_color', 'border-green-100': 'border_color',
                  'border-green-200': 'border_color', 'border-green-300': 'border_color',
                  'border-green-400': 'border_color', 'border-green-500': 'border_color',
                  'border-green-600': 'border_color', 'border-green-700': 'border_color',
                  'border-green-800': 'border_color', 'border-green-900': 'border_color',
                  'border-teal-100': 'border_color', 'border-teal-200': 'border_color',
                  'border-teal-300': 'border_color', 'border-teal-400': 'border_color',
                  'border-teal-500': 'border_color', 'border-teal-600': 'border_color',
                  'border-teal-700': 'border_color', 'border-teal-800': 'border_color',
                  'border-teal-900': 'border_color', 'border-blue-100': 'border_color',
                  'border-blue-200': 'border_color', 'border-blue-300': 'border_color',
                  'border-blue-400': 'border_color', 'border-blue-500': 'border_color',
                  'border-blue-600': 'border_color', 'border-blue-700': 'border_color',
                  'border-blue-800': 'border_color', 'border-blue-900': 'border_color',
                  'border-indigo-100': 'border_color', 'border-indigo-200': 'border_color',
                  'border-indigo-300': 'border_color', 'border-indigo-400': 'border_color',
                  'border-indigo-500': 'border_color', 'border-indigo-600': 'border_color',
                  'border-indigo-700': 'border_color', 'border-indigo-800': 'border_color',
                  'border-indigo-900': 'border_color', 'border-purple-100': 'border_color',
                  'border-purple-200': 'border_color', 'border-purple-300': 'border_color',
                  'border-purple-400': 'border_color', 'border-purple-500': 'border_color',
                  'border-purple-600': 'border_color', 'border-purple-700': 'border_color',
                  'border-purple-800': 'border_color', 'border-purple-900': 'border_color',
                  'border-pink-100': 'border_color', 'border-pink-200': 'border_color',
                  'border-pink-300': 'border_color', 'border-pink-400': 'border_color',
                  'border-pink-500': 'border_color', 'border-pink-600': 'border_color',
                  'border-pink-700': 'border_color', 'border-pink-800': 'border_color',
                  'border-pink-900': 'border_color', 'border-solid': 'border_style', 'border-dashed': 'border_style',
                  'border-dotted': 'border_style', 'border-none': 'border_style', 'border': 'border_width',
                  'border-0': 'border_width', 'border-2': 'border_width', 'border-4': 'border_width',
                  'border-8': 'border_width', 'border-t': 'border_width', 'border-r': 'border_width',
                  'border-b': 'border_width', 'border-l': 'border_width', 'border-t-0': 'border_width',
                  'border-r-0': 'border_width', 'border-b-0': 'border_width', 'border-l-0': 'border_width',
                  'border-t-2': 'border_width', 'border-r-2': 'border_width', 'border-b-2': 'border_width',
                  'border-l-2': 'border_width', 'border-t-4': 'border_width', 'border-r-4': 'border_width',
                  'border-b-4': 'border_width', 'border-l-4': 'border_width', 'border-t-8': 'border_width',
                  'border-r-8': 'border_width', 'border-b-8': 'border_width', 'border-l-8': 'border_width',
                  'rounded-none': 'border_radius', 'rounded-sm': 'border_radius', 'rounded': 'border_radius',
                  'rounded-lg': 'border_radius', 'rounded-full': 'border_radius', 'rounded-t-none': 'border_radius',
                  'rounded-r-none': 'border_radius', 'rounded-b-none': 'border_radius',
                  'rounded-l-none': 'border_radius', 'rounded-t-sm': 'border_radius', 'rounded-r-sm': 'border_radius',
                  'rounded-b-sm': 'border_radius', 'rounded-l-sm': 'border_radius', 'rounded-t': 'border_radius',
                  'rounded-r': 'border_radius', 'rounded-b': 'border_radius', 'rounded-l': 'border_radius',
                  'rounded-t-lg': 'border_radius', 'rounded-r-lg': 'border_radius', 'rounded-b-lg': 'border_radius',
                  'rounded-l-lg': 'border_radius', 'rounded-t-full': 'border_radius', 'rounded-r-full': 'border_radius',
                  'rounded-b-full': 'border_radius', 'rounded-l-full': 'border_radius',
                  'rounded-tl-none': 'border_radius', 'rounded-tr-none': 'border_radius',
                  'rounded-br-none': 'border_radius', 'rounded-bl-none': 'border_radius',
                  'rounded-tl-sm': 'border_radius', 'rounded-tr-sm': 'border_radius', 'rounded-br-sm': 'border_radius',
                  'rounded-bl-sm': 'border_radius', 'rounded-tl': 'border_radius', 'rounded-tr': 'border_radius',
                  'rounded-br': 'border_radius', 'rounded-bl': 'border_radius', 'rounded-tl-lg': 'border_radius',
                  'rounded-tr-lg': 'border_radius', 'rounded-br-lg': 'border_radius', 'rounded-bl-lg': 'border_radius',
                  'rounded-tl-full': 'border_radius', 'rounded-tr-full': 'border_radius',
                  'rounded-br-full': 'border_radius', 'rounded-bl-full': 'border_radius', 'flex-row': 'flex_direction',
                  'flex-row-reverse': 'flex_direction', 'flex-col': 'flex_direction',
                  'flex-col-reverse': 'flex_direction', 'flex-no-wrap': 'flex_wrap', 'flex-wrap': 'flex_wrap',
                  'flex-wrap-reverse': 'flex_wrap', 'items-stretch': 'align_items', 'items-start': 'align_items',
                  'items-center': 'align_items', 'items-end': 'align_items', 'items-baseline': 'align_items',
                  'content-start': 'align_content', 'content-center': 'align_content', 'content-end': 'align_content',
                  'content-between': 'align_content', 'content-around': 'align_content', 'self-auto': 'align_self',
                  'self-start': 'align_self', 'self-center': 'align_self', 'self-end': 'align_self',
                  'self-stretch': 'align_self', 'justify-start': 'justify_content', 'justify-center': 'justify_content',
                  'justify-end': 'justify_content', 'justify-between': 'justify_content',
                  'justify-around': 'justify_content', 'flex-initial': 'flex', 'flex-1': 'flex', 'flex-auto': 'flex',
                  'flex-none': 'flex', 'flex-grow': 'flex_grow', 'flex-grow-0': 'flex_grow',
                  'flex-shrink': 'flex_shrink', 'flex-shrink-0': 'flex_shrink', 'order-first': 'order',
                  'order-last': 'order', 'order-none': 'order', 'order-1': 'order', 'order-2': 'order',
                  'order-3': 'order', 'order-4': 'order', 'order-5': 'order', 'order-6': 'order', 'order-7': 'order',
                  'order-8': 'order', 'order-9': 'order', 'order-10': 'order', 'order-11': 'order', 'order-12': 'order',
                  'p-0': 'padding', 'p-1': 'padding', 'p-2': 'padding', 'p-3': 'padding', 'p-4': 'padding',
                  'p-5': 'padding', 'p-6': 'padding', 'p-8': 'padding', 'p-10': 'padding', 'p-12': 'padding',
                  'p-16': 'padding', 'p-20': 'padding', 'p-24': 'padding', 'p-32': 'padding', 'p-40': 'padding',
                  'p-48': 'padding', 'p-56': 'padding', 'p-64': 'padding', 'p-px': 'padding', 'py-0': 'padding',
                  'py-1': 'padding', 'py-2': 'padding', 'py-3': 'padding', 'py-4': 'padding', 'py-5': 'padding',
                  'py-6': 'padding', 'py-8': 'padding', 'py-10': 'padding', 'py-12': 'padding', 'py-16': 'padding',
                  'py-20': 'padding', 'py-24': 'padding', 'py-32': 'padding', 'py-40': 'padding', 'py-48': 'padding',
                  'py-56': 'padding', 'py-64': 'padding', 'py-px': 'padding', 'px-0': 'padding', 'px-1': 'padding',
                  'px-2': 'padding', 'px-3': 'padding', 'px-4': 'padding', 'px-5': 'padding', 'px-6': 'padding',
                  'px-8': 'padding', 'px-10': 'padding', 'px-12': 'padding', 'px-16': 'padding', 'px-20': 'padding',
                  'px-24': 'padding', 'px-32': 'padding', 'px-40': 'padding', 'px-48': 'padding', 'px-56': 'padding',
                  'px-64': 'padding', 'px-px': 'padding', 'pt-0': 'padding', 'pt-1': 'padding', 'pt-2': 'padding',
                  'pt-3': 'padding', 'pt-4': 'padding', 'pt-5': 'padding', 'pt-6': 'padding', 'pt-8': 'padding',
                  'pt-10': 'padding', 'pt-12': 'padding', 'pt-16': 'padding', 'pt-20': 'padding', 'pt-24': 'padding',
                  'pt-32': 'padding', 'pt-40': 'padding', 'pt-48': 'padding', 'pt-56': 'padding', 'pt-64': 'padding',
                  'pt-px': 'padding', 'pr-0': 'padding', 'pr-1': 'padding', 'pr-2': 'padding', 'pr-3': 'padding',
                  'pr-4': 'padding', 'pr-5': 'padding', 'pr-6': 'padding', 'pr-8': 'padding', 'pr-10': 'padding',
                  'pr-12': 'padding', 'pr-16': 'padding', 'pr-20': 'padding', 'pr-24': 'padding', 'pr-32': 'padding',
                  'pr-40': 'padding', 'pr-48': 'padding', 'pr-56': 'padding', 'pr-64': 'padding', 'pr-px': 'padding',
                  'pb-0': 'padding', 'pb-1': 'padding', 'pb-2': 'padding', 'pb-3': 'padding', 'pb-4': 'padding',
                  'pb-5': 'padding', 'pb-6': 'padding', 'pb-8': 'padding', 'pb-10': 'padding', 'pb-12': 'padding',
                  'pb-16': 'padding', 'pb-20': 'padding', 'pb-24': 'padding', 'pb-32': 'padding', 'pb-40': 'padding',
                  'pb-48': 'padding', 'pb-56': 'padding', 'pb-64': 'padding', 'pb-px': 'padding', 'pl-0': 'padding',
                  'pl-1': 'padding', 'pl-2': 'padding', 'pl-3': 'padding', 'pl-4': 'padding', 'pl-5': 'padding',
                  'pl-6': 'padding', 'pl-8': 'padding', 'pl-10': 'padding', 'pl-12': 'padding', 'pl-16': 'padding',
                  'pl-20': 'padding', 'pl-24': 'padding', 'pl-32': 'padding', 'pl-40': 'padding', 'pl-48': 'padding',
                  'pl-56': 'padding', 'pl-64': 'padding', 'pl-px': 'padding', 'm-0': 'margin', 'm-1': 'margin',
                  'm-2': 'margin', 'm-3': 'margin', 'm-4': 'margin', 'm-5': 'margin', 'm-6': 'margin', 'm-8': 'margin',
                  'm-10': 'margin', 'm-12': 'margin', 'm-16': 'margin', 'm-20': 'margin', 'm-24': 'margin',
                  'm-32': 'margin', 'm-40': 'margin', 'm-48': 'margin', 'm-56': 'margin', 'm-64': 'margin',
                  'm-auto': 'margin', 'm-px': 'margin', '-m-1': 'margin', '-m-2': 'margin', '-m-3': 'margin',
                  '-m-4': 'margin', '-m-5': 'margin', '-m-6': 'margin', '-m-8': 'margin', '-m-10': 'margin',
                  '-m-12': 'margin', '-m-16': 'margin', '-m-20': 'margin', '-m-24': 'margin', '-m-32': 'margin',
                  '-m-40': 'margin', '-m-48': 'margin', '-m-56': 'margin', '-m-64': 'margin', '-m-px': 'margin',
                  'my-0': 'margin', 'my-1': 'margin', 'my-2': 'margin', 'my-3': 'margin', 'my-4': 'margin',
                  'my-5': 'margin', 'my-6': 'margin', 'my-8': 'margin', 'my-10': 'margin', 'my-12': 'margin',
                  'my-16': 'margin', 'my-20': 'margin', 'my-24': 'margin', 'my-32': 'margin', 'my-40': 'margin',
                  'my-48': 'margin', 'my-56': 'margin', 'my-64': 'margin', 'my-auto': 'margin', 'my-px': 'margin',
                  '-my-1': 'margin', '-my-2': 'margin', '-my-3': 'margin', '-my-4': 'margin', '-my-5': 'margin',
                  '-my-6': 'margin', '-my-8': 'margin', '-my-10': 'margin', '-my-12': 'margin', '-my-16': 'margin',
                  '-my-20': 'margin', '-my-24': 'margin', '-my-32': 'margin', '-my-40': 'margin', '-my-48': 'margin',
                  '-my-56': 'margin', '-my-64': 'margin', '-my-px': 'margin', 'mx-0': 'margin', 'mx-1': 'margin',
                  'mx-2': 'margin', 'mx-3': 'margin', 'mx-4': 'margin', 'mx-5': 'margin', 'mx-6': 'margin',
                  'mx-8': 'margin', 'mx-10': 'margin', 'mx-12': 'margin', 'mx-16': 'margin', 'mx-20': 'margin',
                  'mx-24': 'margin', 'mx-32': 'margin', 'mx-40': 'margin', 'mx-48': 'margin', 'mx-56': 'margin',
                  'mx-64': 'margin', 'mx-auto': 'margin', 'mx-px': 'margin', '-mx-1': 'margin', '-mx-2': 'margin',
                  '-mx-3': 'margin', '-mx-4': 'margin', '-mx-5': 'margin', '-mx-6': 'margin', '-mx-8': 'margin',
                  '-mx-10': 'margin', '-mx-12': 'margin', '-mx-16': 'margin', '-mx-20': 'margin', '-mx-24': 'margin',
                  '-mx-32': 'margin', '-mx-40': 'margin', '-mx-48': 'margin', '-mx-56': 'margin', '-mx-64': 'margin',
                  '-mx-px': 'margin', 'mt-0': 'margin', 'mt-1': 'margin', 'mt-2': 'margin', 'mt-3': 'margin',
                  'mt-4': 'margin', 'mt-5': 'margin', 'mt-6': 'margin', 'mt-8': 'margin', 'mt-10': 'margin',
                  'mt-12': 'margin', 'mt-16': 'margin', 'mt-20': 'margin', 'mt-24': 'margin', 'mt-32': 'margin',
                  'mt-40': 'margin', 'mt-48': 'margin', 'mt-56': 'margin', 'mt-64': 'margin', 'mt-auto': 'margin',
                  'mt-px': 'margin', '-mt-1': 'margin', '-mt-2': 'margin', '-mt-3': 'margin', '-mt-4': 'margin',
                  '-mt-5': 'margin', '-mt-6': 'margin', '-mt-8': 'margin', '-mt-10': 'margin', '-mt-12': 'margin',
                  '-mt-16': 'margin', '-mt-20': 'margin', '-mt-24': 'margin', '-mt-32': 'margin', '-mt-40': 'margin',
                  '-mt-48': 'margin', '-mt-56': 'margin', '-mt-64': 'margin', '-mt-px': 'margin', 'mr-0': 'margin',
                  'mr-1': 'margin', 'mr-2': 'margin', 'mr-3': 'margin', 'mr-4': 'margin', 'mr-5': 'margin',
                  'mr-6': 'margin', 'mr-8': 'margin', 'mr-10': 'margin', 'mr-12': 'margin', 'mr-16': 'margin',
                  'mr-20': 'margin', 'mr-24': 'margin', 'mr-32': 'margin', 'mr-40': 'margin', 'mr-48': 'margin',
                  'mr-56': 'margin', 'mr-64': 'margin', 'mr-auto': 'margin', 'mr-px': 'margin', '-mr-1': 'margin',
                  '-mr-2': 'margin', '-mr-3': 'margin', '-mr-4': 'margin', '-mr-5': 'margin', '-mr-6': 'margin',
                  '-mr-8': 'margin', '-mr-10': 'margin', '-mr-12': 'margin', '-mr-16': 'margin', '-mr-20': 'margin',
                  '-mr-24': 'margin', '-mr-32': 'margin', '-mr-40': 'margin', '-mr-48': 'margin', '-mr-56': 'margin',
                  '-mr-64': 'margin', '-mr-px': 'margin', 'mb-0': 'margin', 'mb-1': 'margin', 'mb-2': 'margin',
                  'mb-3': 'margin', 'mb-4': 'margin', 'mb-5': 'margin', 'mb-6': 'margin', 'mb-8': 'margin',
                  'mb-10': 'margin', 'mb-12': 'margin', 'mb-16': 'margin', 'mb-20': 'margin', 'mb-24': 'margin',
                  'mb-32': 'margin', 'mb-40': 'margin', 'mb-48': 'margin', 'mb-56': 'margin', 'mb-64': 'margin',
                  'mb-auto': 'margin', 'mb-px': 'margin', '-mb-1': 'margin', '-mb-2': 'margin', '-mb-3': 'margin',
                  '-mb-4': 'margin', '-mb-5': 'margin', '-mb-6': 'margin', '-mb-8': 'margin', '-mb-10': 'margin',
                  '-mb-12': 'margin', '-mb-16': 'margin', '-mb-20': 'margin', '-mb-24': 'margin', '-mb-32': 'margin',
                  '-mb-40': 'margin', '-mb-48': 'margin', '-mb-56': 'margin', '-mb-64': 'margin', '-mb-px': 'margin',
                  'ml-0': 'margin', 'ml-1': 'margin', 'ml-2': 'margin', 'ml-3': 'margin', 'ml-4': 'margin',
                  'ml-5': 'margin', 'ml-6': 'margin', 'ml-8': 'margin', 'ml-10': 'margin', 'ml-12': 'margin',
                  'ml-16': 'margin', 'ml-20': 'margin', 'ml-24': 'margin', 'ml-32': 'margin', 'ml-40': 'margin',
                  'ml-48': 'margin', 'ml-56': 'margin', 'ml-64': 'margin', 'ml-auto': 'margin', 'ml-px': 'margin',
                  '-ml-1': 'margin', '-ml-2': 'margin', '-ml-3': 'margin', '-ml-4': 'margin', '-ml-5': 'margin',
                  '-ml-6': 'margin', '-ml-8': 'margin', '-ml-10': 'margin', '-ml-12': 'margin', '-ml-16': 'margin',
                  '-ml-20': 'margin', '-ml-24': 'margin', '-ml-32': 'margin', '-ml-40': 'margin', '-ml-48': 'margin',
                  '-ml-56': 'margin', '-ml-64': 'margin', '-ml-px': 'margin', 'w-0': 'width', 'w-1': 'width',
                  'w-2': 'width', 'w-3': 'width', 'w-4': 'width', 'w-5': 'width', 'w-6': 'width', 'w-8': 'width',
                  'w-10': 'width', 'w-12': 'width', 'w-16': 'width', 'w-20': 'width', 'w-24': 'width', 'w-32': 'width',
                  'w-40': 'width', 'w-48': 'width', 'w-56': 'width', 'w-64': 'width', 'w-auto': 'width',
                  'w-px': 'width', 'w-1/2': 'width', 'w-1/3': 'width', 'w-2/3': 'width', 'w-1/4': 'width',
                  'w-2/4': 'width', 'w-3/4': 'width', 'w-1/5': 'width', 'w-2/5': 'width', 'w-3/5': 'width',
                  'w-4/5': 'width', 'w-1/6': 'width', 'w-2/6': 'width', 'w-3/6': 'width', 'w-4/6': 'width',
                  'w-5/6': 'width', 'w-1/12': 'width', 'w-2/12': 'width', 'w-3/12': 'width', 'w-4/12': 'width',
                  'w-5/12': 'width', 'w-6/12': 'width', 'w-7/12': 'width', 'w-8/12': 'width', 'w-9/12': 'width',
                  'w-10/12': 'width', 'w-11/12': 'width', 'w-full': 'width', 'w-screen': 'width',
                  'min-w-0': 'min_width', 'min-w-full': 'min_width', 'max-w-xs': 'max_width', 'max-w-sm': 'max_width',
                  'max-w-md': 'max_width', 'max-w-lg': 'max_width', 'max-w-xl': 'max_width', 'max-w-2xl': 'max_width',
                  'max-w-3xl': 'max_width', 'max-w-4xl': 'max_width', 'max-w-5xl': 'max_width',
                  'max-w-6xl': 'max_width', 'max-w-full': 'max_width', 'h-0': 'height', 'h-1': 'height',
                  'h-2': 'height', 'h-3': 'height', 'h-4': 'height', 'h-5': 'height', 'h-6': 'height', 'h-8': 'height',
                  'h-10': 'height', 'h-12': 'height', 'h-16': 'height', 'h-20': 'height', 'h-24': 'height',
                  'h-32': 'height', 'h-40': 'height', 'h-48': 'height', 'h-56': 'height', 'h-64': 'height',
                  'h-auto': 'height', 'h-px': 'height', 'h-full': 'height', 'h-screen': 'height',
                  'min-h-0': 'min_height', 'min-h-full': 'min_height', 'min-h-screen': 'min_height',
                  'max-h-full': 'max_height', 'max-h-screen': 'max_height', 'border-collapse': 'border_collapse',
                  'border-separate': 'border_collapse', 'table-auto': 'table_layout', 'table-fixed': 'table_layout',
                  'shadow': 'box_shadow', 'shadow-md': 'box_shadow', 'shadow-lg': 'box_shadow',
                  'shadow-xl': 'box_shadow', 'shadow-2xl': 'box_shadow', 'shadow-inner': 'box_shadow',
                  'shadow-outline': 'box_shadow', 'shadow-none': 'box_shadow', 'opacity-100': 'opacity',
                  'opacity-75': 'opacity', 'opacity-50': 'opacity', 'opacity-25': 'opacity', 'opacity-0': 'opacity',
                  'appearance-none': 'appearance', 'cursor-auto': 'cursor', 'cursor-default': 'cursor',
                  'cursor-pointer': 'cursor', 'cursor-wait': 'cursor', 'cursor-text': 'cursor', 'cursor-move': 'cursor',
                  'cursor-not-allowed': 'cursor', 'outline-none': 'outline', 'pointer-events-none': 'pointer_events',
                  'pointer-events-auto': 'pointer_events', 'resize-none': 'resize', 'resize': 'resize',
                  'resize-y': 'resize', 'resize-x': 'resize', 'select-none': 'user_select',
                  'select-text': 'user_select', 'select-all': 'user_select', 'select-auto': 'user_select',
                  'fill-current': 'fill', 'stroke-current': 'stroke'}


    def set_class(self, tw_class, modifier=''):
        # Set Tailwind class
        if modifier and modifier not in Tailwind.pseudo_classes:
            raise Exception(f'No Tailwind pseudo-class (modifier) named {modifier}')
        if tw_class not in Tailwind.tw_reverse_dict:
            raise Exception(f'No Tailwind class named {tw_class}')
        class_list = self.classes.split()
        if not modifier:
            for i in class_list:
                if i in Tailwind.tw_dict[Tailwind.tw_reverse_dict[tw_class]]:
                    class_list.remove(i)
            class_list.append(tw_class)
        else:
            tw_dict_modified = [f'{modifier}:' + i for i in Tailwind.tw_dict[Tailwind.tw_reverse_dict[tw_class]]]
            tw_class_modified = f'{modifier}:{tw_class}'
            for i in class_list:
                if i in tw_dict_modified:
                    class_list.remove(i)
            class_list.append(tw_class_modified)
        self.classes = ' '.join(class_list)
        return self.classes

    def set_classes(self, class_list):
        # Takes a string of tailwind classes and sets them all
        for c in class_list.split():
            c = c.split(':')
            if len(c) > 1:
                self.set_class(c[1], c[0])
            else:
                self.set_class(c[0])



