'''
Created on 16.11.2022

@author: wf
'''
# Justpy global configuration variables (deprecated as of 0.11)
# importing justpy_config does not set the variables if Compatbility.version is set
AGGRID=None
AGGRID_ENTERPRISE=None
BOKEH=None
CRASH=None
COOKIE_MAX_AGE=None
CRASH=None
DEBUG=None
DECKGL=None
FAVICON=None
FRONTEND_ENGINE_TYPE=None
FRONTEND_ENGINE_LIBS=None
HIGHCHARTS=None
HOST=None
KATEX=None
LATENCY=None
LOGGING_LEVEL=None
MEMORY_DEBUG=None
NO_INTERNET=None
PLOTLY=None
PORT=None
SECRET_KEY=None
SESSION_COOKIE_NAME=None
SESSIONS=None
SSL_CERTFILE=None
SSL_KEYFILE=None
SSL_VERSION=None
STATIC_DIRECTORY=None
STATIC_NAME=None
STATIC_ROUTE=None
QUASAR=None
QUASAR_VERSION=None
TAILWIND=None
UVICORN_LOGGING_LEVEL=None
VEGA=None
VERBOSE=None

