#!/bin/bash
# WF 2022-08-20
pip install aiohttp asynctest green pandas psutil selenium  webdriver-manager
for testmodule in tests/test*.py
do
 echo "testing $testmodule ..."
  green $testmodule
done 
