#!/bin/bash
# WF 2022-08-20
install_packages() {
  pip install aiohttp asynctest green pandas psutil selenium  webdriver-manager
}

modulewise_test() {
  for testmodule in tests/test*.py
  do
    echo "testing $testmodule ..."
    green $testmodule
  done 
}

install_packages
modulewise_test
green tests
